### ISSUE TITLE
Armor value for the cosmetic chestplate is not very logical compared to that of the pants

### ISSUE THREAD

**Issue by liach** [hanakocz/Railcraft-Cosmetic-Additions#11]

**Comment by hanakocz** [comment]
It is {1, 3, 2, 1} for helm, chest, legs, boots, same as vanilla leather armor. What else it should be?

**Comment by liach** [comment]
the value for chest and legs are inverted, I think.

**Comment by hanakocz** [comment]
I checked 1.7.10 version and it also has it same. At least in code.
